#include<stdio.h>
void main()
{
   int arr1[100],arr2[100],arr3[100],n1,n2,n3,i,j,m=0,sum=0,count=0;
   printf("Enter the number of elements in array1 : ");
   scanf("%d",&n1);
   for(i=0;i<n1;i++)
   {
       scanf("%d",&arr1[i]);
   }
   printf("The first digit is : ");
   for(i=0;i<n1;i++)
   {
       printf("%d",arr1[i]);
   }
   printf("\n\nEnter the number of elements in array2 : ");
   scanf("%d",&n2);
   for(i=0;i<n2;i++)
   {
       scanf("%d",&arr2[i]);
   }
   printf("The second digit is : ");
   for(i=0;i<n2;i++)
   {
       printf("%d",arr2[i]);
   }
   if(n1<n2)
   {
       for(i=n1-1;i>=0;i--)
       {
          for(j=n2-1;j==n2-1;j--)
          {
                  sum=arr1[i]+arr2[j]+sum;
                  printf("tsum=%d",sum);
                  if(sum<10)
                  {
                   arr3[m]=sum;
                   printf("ssum=%d",sum);
                   m++;
                   if(i!=0){
                      count++;
                   }
                   sum=0;
                  }
                  else
                  {
                   sum=sum%10;
                   printf("msum=%d",sum);
                   arr3[m]=sum;
                   m++;
                   count++;
                   sum=1;
                  }
           }
           n2--;
        }
        printf("\nn2=%d",n2);
        i=n2-1;
        printf("\nn2=%d",i);
      for(i=i;i>=0;i--)
      {
          printf("aar[1]=%d i=%d",arr2[i],i);
          sum=sum+arr2[i];
          printf("tsum=%d",sum);
          if(sum<10)
            {
                arr3[m]=sum;
                printf("ssum=%d",sum);
                m++;
                if(i!=0){
                  count++;
                }
                sum=0;
            }
            else
            {
                sum=sum%10;
                arr3[m]=sum;
                printf("msum=%d",sum);
                m++;
                count++;
                if(i==0)
                {
                    arr3[m]=1;
                }
                sum=1;
            }
            n2--;
      }
   }
   else
   {
       for(i=n2-1;i>=0;i--)
       {
          for(j=n1-1;j==n1-1;j--)
          {
                  sum=arr2[i]+arr1[j]+sum;
                  printf("tsum=%d",sum);
                  if(sum<10)
                  {
                   arr3[m]=sum;
                   printf("ssum=%d",sum);
                   m++;
                   if(i!=0)
                   {
                       count++;
                   }
                   sum=0;
                  }
                  else
                  {
                   sum=sum%10;
                   printf("msum=%d",sum);
                   arr3[m]=sum;
                   m++;
                   count++;
                       if(i==0)
                       {
                           arr3[m]=1;
                       }
                   sum=1;
                  }
           }
           n1--;
        }
        printf("\nn1=%d",n1);
        i=n1-1;
        printf("\nn1=%d",i);
      for(i=i;i>=0;i--)
      {
          printf("\naar[1]=%d i=%d",arr1[i],i);
          sum=sum+arr1[i];
          printf("\ntsum=%d",sum);
          if(sum<10)
            {
                arr3[m]=sum;
                printf("\nssum=%d",sum);
                m++;
                if(i!=0)
                {
                   count++;
                }
                sum=0;
            }
            else
            {
                sum=sum%10;
                arr3[m]=sum;
                m++;
                count++;
                 if(i==0)
                   {
                         arr3[m]=1;
                   }
                printf("\nmsum=%d arr3=%d count=%d i=%d",sum,arr3[m],count,i);
                sum=1;
            }
      }
   }
   for(i=count;i>=0;i--)
   {
       printf("%d",arr3[i]);
   }
}

